FROM ubuntu:18.04

WORKDIR /app

RUN apt update && apt install -y ca-certificates curl gnupg &&  \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

ENV NODE_MAJOR=20
RUN apt update && apt install -y nodejs && \
    apt-get install -y chromium-browser

COPY ./scrapper/package.json .

RUN npm install

COPY ./scrapper .

RUN npm run build

EXPOSE 3000

CMD [ "node", "dist/main.js" ]